final mockAllbreeds =[
{
"weight": {
"imperial": "7  -  10",
"metric": "3 - 5"
},
"id": "abys",
"name": "Abyssinian",
"cfa_url": "http://cfa.org/Breeds/BreedsAB/Abyssinian.aspx",
"vetstreet_url": "http://www.vetstreet.com/cats/abyssinian",
"vcahospitals_url": "https://vcahospitals.com/know-your-pet/cat-breeds/abyssinian",
"temperament": "Active, Energetic, Independent, Intelligent, Gentle",
"origin": "Egypt",
"country_codes": "EG",
"country_code": "EG",
"description": "The Abyssinian is easy to care for, and a joy to have in your home. They’re affectionate cats and love both people and other animals.",
"life_span": "14 - 15",
"indoor": 0,
"lap": 1,
"alt_names": "",
"adaptability": 5,
"affection_level": 5,
"child_friendly": 3,
"dog_friendly": 4,
"energy_level": 5,
"grooming": 1,
"health_issues": 2,
"intelligence": 5,
"shedding_level": 2,
"social_needs": 5,
"stranger_friendly": 5,
"vocalisation": 1,
"experimental": 0,
"hairless": 0,
"natural": 1,
"rare": 0,
"rex": 0,
"suppressed_tail": 0,
"short_legs": 0,
"wikipedia_url": "https://en.wikipedia.org/wiki/Abyssinian_(cat)",
"hypoallergenic": 0,
"reference_image_id": "0XYvRd7oD"
},
{
"weight": {
"imperial": "7 - 10",
"metric": "3 - 5"
},
"id": "aege",
"name": "Aegean",
"vetstreet_url": "http://www.vetstreet.com/cats/aegean-cat",
"temperament": "Affectionate, Social, Intelligent, Playful, Active",
"origin": "Greece",
"country_codes": "GR",
"country_code": "GR",
"description": "Native to the Greek islands known as the Cyclades in the Aegean Sea, these are natural cats, meaning they developed without humans getting involved in their breeding. As a breed, Aegean Cats are rare, although they are numerous on their home islands. They are generally friendly toward people and can be excellent cats for families with children.",
"life_span": "9 - 12",
"indoor": 0,
"alt_names": "",
"adaptability": 5,
"affection_level": 4,
"child_friendly": 4,
"dog_friendly": 4,
"energy_level": 3,
"grooming": 3,
"health_issues": 1,
"intelligence": 3,
"shedding_level": 3,
"social_needs": 4,
"stranger_friendly": 4,
"vocalisation": 3,
"experimental": 0,
"hairless": 0,
"natural": 0,
"rare": 0,
"rex": 0,
"suppressed_tail": 0,
"short_legs": 0,
"wikipedia_url": "https://en.wikipedia.org/wiki/Aegean_cat",
"hypoallergenic": 0,
"reference_image_id": "ozEvzdVM-"
},
{
"weight": {
"imperial": "7 - 16",
"metric": "3 - 7"
},
"id": "abob",
"name": "American Bobtail",
"cfa_url": "http://cfa.org/Breeds/BreedsAB/AmericanBobtail.aspx",
"vetstreet_url": "http://www.vetstreet.com/cats/american-bobtail",
"vcahospitals_url": "https://vcahospitals.com/know-your-pet/cat-breeds/american-bobtail",
"temperament": "Intelligent, Interactive, Lively, Playful, Sensitive",
"origin": "United States",
"country_codes": "US",
"country_code": "US",
"description": "American Bobtails are loving and incredibly intelligent cats possessing a distinctive wild appearance. They are extremely interactive cats that bond with their human family with great devotion.",
"life_span": "11 - 15",
"indoor": 0,
"lap": 1,
"alt_names": "",
"adaptability": 5,
"affection_level": 5,
"child_friendly": 4,
"dog_friendly": 5,
"energy_level": 3,
"grooming": 1,
"health_issues": 1,
"intelligence": 5,
"shedding_level": 3,
"social_needs": 3,
"stranger_friendly": 3,
"vocalisation": 3,
"experimental": 0,
"hairless": 0,
"natural": 0,
"rare": 0,
"rex": 0,
"suppressed_tail": 1,
"short_legs": 0,
"wikipedia_url": "https://en.wikipedia.org/wiki/American_Bobtail",
"hypoallergenic": 0,
"reference_image_id": "hBXicehMA"
},
{
"weight": {
"imperial": "5 - 10",
"metric": "2 - 5"
},
"id": "acur",
"name": "American Curl",
"cfa_url": "http://cfa.org/Breeds/BreedsAB/AmericanCurl.aspx",
"vetstreet_url": "http://www.vetstreet.com/cats/american-curl",
"vcahospitals_url": "https://vcahospitals.com/know-your-pet/cat-breeds/american-curl",
"temperament": "Affectionate, Curious, Intelligent, Interactive, Lively, Playful, Social",
"origin": "United States",
"country_codes": "US",
"country_code": "US",
"description": "Distinguished by truly unique ears that curl back in a graceful arc, offering an alert, perky, happily surprised expression, they cause people to break out into a big smile when viewing their first Curl. Curls are very people-oriented, faithful, affectionate soulmates, adjusting remarkably fast to other pets, children, and new situations.",
"life_span": "12 - 16",
"indoor": 0,
"lap": 1,
"alt_names": "",
"adaptability": 5,
"affection_level": 5,
"child_friendly": 4,
"dog_friendly": 5,
"energy_level": 3,
"grooming": 2,
"health_issues": 1,
"intelligence": 3,
"shedding_level": 3,
"social_needs": 3,
"stranger_friendly": 3,
"vocalisation": 3,
"experimental": 0,
"hairless": 0,
"natural": 0,
"rare": 0,
"rex": 0,
"suppressed_tail": 0,
"short_legs": 0,
"wikipedia_url": "https://en.wikipedia.org/wiki/American_Curl",
"hypoallergenic": 0,
"reference_image_id": "xnsqonbjW"
},
{
"weight": {
"imperial": "8 - 15",
"metric": "4 - 7"
},
"id": "asho",
"name": "American Shorthair",
"cfa_url": "http://cfa.org/Breeds/BreedsAB/AmericanShorthair.aspx",
"vetstreet_url": "http://www.vetstreet.com/cats/american-shorthair",
"vcahospitals_url": "https://vcahospitals.com/know-your-pet/cat-breeds/american-shorthair",
"temperament": "Active, Curious, Easy Going, Playful, Calm",
"origin": "United States",
"country_codes": "US",
"country_code": "US",
"description": "The American Shorthair is known for its longevity, robust health, good looks, sweet personality, and amiability with children, dogs, and other pets.",
"life_span": "15 - 17",
"indoor": 0,
"lap": 1,
"alt_names": "Domestic Shorthair",
"adaptability": 5,
"affection_level": 5,
"child_friendly": 4,
"dog_friendly": 5,
"energy_level": 3,
"grooming": 1,
"health_issues": 3,
"intelligence": 3,
"shedding_level": 3,
"social_needs": 4,
"stranger_friendly": 3,
"vocalisation": 3,
"experimental": 0,
"hairless": 0,
"natural": 1,
"rare": 0,
"rex": 0,
"suppressed_tail": 0,
"short_legs": 0,
"wikipedia_url": "https://en.wikipedia.org/wiki/American_Shorthair",
"hypoallergenic": 0,
"reference_image_id": "JFPROfGtQ"
}
];
final mockBreedsBynameEmpy=[];
final mockBreedsByname=[
  {
    "weight": {
      "imperial": "7  -  10",
      "metric": "3 - 5"
    },
    "id": "abys",
    "name": "Abyssinian",
    "cfa_url": "http://cfa.org/Breeds/BreedsAB/Abyssinian.aspx",
    "vetstreet_url": "http://www.vetstreet.com/cats/abyssinian",
    "vcahospitals_url": "https://vcahospitals.com/know-your-pet/cat-breeds/abyssinian",
    "temperament": "Active, Energetic, Independent, Intelligent, Gentle",
    "origin": "Egypt",
    "country_codes": "EG",
    "country_code": "EG",
    "description": "The Abyssinian is easy to care for, and a joy to have in your home. They’re affectionate cats and love both people and other animals.",
    "life_span": "14 - 15",
    "indoor": 0,
    "lap": 1,
    "alt_names": "",
    "adaptability": 5,
    "affection_level": 5,
    "child_friendly": 3,
    "dog_friendly": 4,
    "energy_level": 5,
    "grooming": 1,
    "health_issues": 2,
    "intelligence": 5,
    "shedding_level": 2,
    "social_needs": 5,
    "stranger_friendly": 5,
    "vocalisation": 1,
    "experimental": 0,
    "hairless": 0,
    "natural": 1,
    "rare": 0,
    "rex": 0,
    "suppressed_tail": 0,
    "short_legs": 0,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Abyssinian_(cat)",
    "hypoallergenic": 0,
    "reference_image_id": "0XYvRd7oD"
  }
];

final mockBreedsImgByid=[
  {
    "id": "xnzzM6MBI",
    "url": "https://cdn2.thecatapi.com/images/xnzzM6MBI.jpg",
    "width": 2592,
    "height": 1629
  },
  {
    "id": "unPP08xOZ",
    "url": "https://cdn2.thecatapi.com/images/unPP08xOZ.jpg",
    "width": 2136,
    "height": 2848
  },
  {
    "id": "N-94oSJ5T",
    "url": "https://cdn2.thecatapi.com/images/N-94oSJ5T.jpg",
    "width": 1920,
    "height": 1280
  },
  {
    "id": "itfFA4NWS",
    "url": "https://cdn2.thecatapi.com/images/itfFA4NWS.jpg",
    "width": 1280,
    "height": 914
  },
  {
    "id": "KWdLHmOqc",
    "url": "https://cdn2.thecatapi.com/images/KWdLHmOqc.jpg",
    "width": 3114,
    "height": 2609
  },
  {
    "id": "0XYvRd7oD",
    "url": "https://cdn2.thecatapi.com/images/0XYvRd7oD.jpg",
    "width": 1204,
    "height": 1445
  },
  {
    "id": "9x1zk_Qdr",
    "url": "https://cdn2.thecatapi.com/images/9x1zk_Qdr.jpg",
    "width": 1204,
    "height": 1107
  },
  {
    "id": "Kq8__jmkT",
    "url": "https://cdn2.thecatapi.com/images/Kq8__jmkT.jpg",
    "width": 1527,
    "height": 1286
  },
  {
    "id": "TGuAku7fM",
    "url": "https://cdn2.thecatapi.com/images/TGuAku7fM.jpg",
    "width": 1920,
    "height": 1279
  },
  {
    "id": "tv8tNeYaU",
    "url": "https://cdn2.thecatapi.com/images/tv8tNeYaU.jpg",
    "width": 1600,
    "height": 1200
  }
];

final listImage=[
  "https://cdn2.thecatapi.com/images/9x1zk_Qdr.jpg",
  "https://cdn2.thecatapi.com/images/Kq8__jmkT.jpg",
  "https://cdn2.thecatapi.com/images/TGuAku7fM.jpg",
  "https://cdn2.thecatapi.com/images/tv8tNeYaU.jpg",

];

